# Download the event log from https://data.4tu.nl/articles/dataset/Road_Traffic_Fine_Management_Process/12683249
input = "../Road_Traffic_Fine_Management_Process.xes.gz"
output = "random_split_logs"
compress_output = true

[[pipeline.mutations]]
type = "SojournStartAdder"
key = "start_timestamp"

[[pipeline.mutations]]
type = "LogSplitter"
frac = 0.5
save_compressed = true
seed = "1..=250"
